name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          lein: 2.9.10

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-

      - name: Install Ragtime core locally
        run: lein install
        working-directory: ./core

      - name: Install Ragtime SQL locally
        run: lein install
        working-directory: ./sql

      - name: Run tests
        run: lein sub test

      - name: Lint code
        run: clj-kondo --lint **/src **/test

      - name: Check formatting
        run: cljfmt check **/src **/test
